language: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install --save-dev @angular-devkit/build-angular
  - npm install @angular/compiler-cli
  - npm install @angular/compiler
script:
  - cd yourney-angular-app
  - ng build --prod
notifications:
  email:
    recipients:
      - edubotdom@alum.us.es
      - danaremar@alum.us.es
      - alesansaa@alum.us.es
      - juanogtir@alum.us.es
      - pabrodgar@alum.us.es
      - javnavpli@alum.us.es
      - jossalase@alum.us.es
      - marlasesc@alum.us.es
    on_success: always
    on_failure: always